

very_sensitive_combinations = [
    ["[*]"],
    ["iam:PassRole"],

    ["backup:PutBackupVaultAccessPolicy"],

    ["codebuild:StartBuild"],
    ["codebuild:StartBuildBatch"],

    ["cognito-identity:UpdateIdentityPool"],
    ["cognito-idp:AdminAddUserToGroup"],
    ["cognito-idp:AdminConfirmSignUp"],
    ["cognito-idp:AdminCreateUser"],
    ["cognito-idp:AdminSetUserPassword"],
    ["cognito-idp:SetUserPoolMfaConfig"],
    ["cognito-idp:UpdateUserPool"],
    ["cognito-idp:AdminUpdateUserAttributes"],
    ["cognito-idp:CreateUserPoolClient"],
    ["cognito-idp:UpdateUserPoolClient"],
    ["cognito-idp:CreateUserImportJob"],
    ["cognito-idp:StartUserImportJob"],
    ["cognito-idp:CreateIdentityProvider"],
    ["cognito-idp:UpdateIdentityProvider"],

    ["ds:ResetUserPassword"],

    ["dynamodb:PutResourcePolicy"],

    ["ec2:ModifyInstanceAttribute"],
    ["ec2:CreateLaunchTemplateVersion", "ec2:CreateLaunchTemplate", "ec2:ModifyLaunchTemplate"],
    ["ec2-instance-connect:SendSSHPublicKey"],
    ["ec2-instance-connect:SendSerialConsoleSSHPublicKey"],

    ["ebs:ListSnapshotBlocks", "ebs:GetSnapshotBlock"],

    ["ecr:GetAuthorizationToken", "ecr:BatchCheckLayerAvailability", "ecr:CompleteLayerUpload", "ecr:InitiateLayerUpload", "ecr:PutImage", "ecr:UploadLayerPart"],
    ["ecr-public:GetAuthorizationToken", "ecr-public:BatchCheckLayerAvailability", "ecr-public:CompleteLayerUpload", "ecr-public:InitiateLayerUpload", "ecr-public:PutImage", "ecr-public:UploadLayerPart"],
    ["ecr:SetRepositoryPolicy"],
    ["ecr-public:SetRepositoryPolicy"],
    ["ecr:PutRegistryPolicy"],

    ["ecs:RegisterTaskDefinition"],
    ["ecs:ExecuteCommand"],

    ["elasticfilesystem:DeleteFileSystemPolicy"],
    ["elasticfilesystem:PutFileSystemPolicy"],

    ["elasticmapreduce:OpenEditorInConsole"],

    ["gamelift:RequestUploadCredentials"],

    ["glue:UpdateDevEndpoint"],
    ["glue:UpdateJob"],

    ["iam:CreatePolicyVersion"],
    ["iam:SetDefaultPolicyVersion"],
    ["iam:CreateAccessKey"],
    ["iam:CreateLoginProfile"],
    ["iam:UpdateLoginProfile"],
    ["iam:UpdateAccessKey"],
    ["iam:CreateServiceSpecificCredential"],
    ["iam:ResetServiceSpecificCredential"],
    ["iam:AttachUserPolicy"],
    ["iam:AttachGroupPolicy"],
    ["iam:AttachRolePolicy"],
    ["iam:PutUserPolicy"],
    ["iam:PutGroupPolicy"],
    ["iam:PutRolePolicy"],
    ["iam:AddUserToGroup"],
    ["iam:UpdateAssumeRolePolicy"],
    ["iam:UploadSSHPublicKey"],
    ["iam:DeactivateMFADevice"],
    ["iam:ResyncMFADevice"],
    ["iam:UpdateSAMLProvider"],
    ["iam:UpdateOpenIDConnectProviderThumbprint"],

    ["iot:OpenTunnel"],

    ["kms:PutKeyPolicy"],
    ["kms:CreateGrant"],

    ["lambda:AddPermission"],
    ["lambda:AddLayerVersionPermission"],
    ["lambda:UpdateFunctionCode"],

    ["lightsail:DownloadDefaultKeyPair"],
    ["lightsail:GetInstanceAccessDetails"],
    ["lightsail:CreateBucketAccessKey"],
    ["lightsail:GetRelationalDatabaseMasterUserPassword"],
    ["lightsail:UpdateRelationalDatabase"],
    ["lightsail:OpenInstancePublicPorts"],
    ["lightsail:PutInstancePublicPorts"],
    ["lightsail:SetResourceAccessForBucket"],
    ["lightsail:UpdateBucket"],
    ["lightsail:UpdateContainerService"],
    ["lightsail:UpdateDomainEntry"],
    ["lightsail:CreateDomainEntry"],

    ["mediapackage:RotateChannelCredentials"],
    ["mediapackage:RotateIngestEndpointCredentials"],

    ["mq:CreateUser"],
    ["mq:UpdateUser"],
    ["mq:UpdateBroker"],

    ["kafka:UpdateSecurity"],

    ["rds:ModifyDBInstance"],

    ["redshift:DescribeClusters", "redshift:GetClusterCredentials"],

    ["redshift:DescribeClusters", "redshift:GetClusterCredentialsWithIAM"],

    ["route53:CreateHostedZone", "route53:ChangeResourceRecordSets", "acm-pca:IssueCertificate",  "acm-pca:GetCertificate"],

    ["sns:AddPermission"],

    ["sqs:AddPermission"],

    ["identitystore:CreateGroupMembership"],
    ["sso:PutInlinePolicyToPermissionSet", "sso:ProvisionPermissionSet"],
    ["sso:AttachManagedPolicyToPermissionSet", "sso:ProvisionPermissionSet"],
    ["sso:AttachCustomerManagedPolicyReferenceToPermissionSet", "sso:ProvisionPermissionSet"],
    ["sso:CreateAccountAssignment"],

    ["s3:PutBucketPolicy"],
    ["s3:PutBucketAcl"],
    ["s3:PutAccessPointPolicy"],
    ["s3:PutObjectAcl"],
    ["s3:PutObjectVersionAcl"],

    ["sagemaker:CreatePresignedNotebookInstanceUrl"],

    ["secretsmanager:GetSecretValue"],
    ["secretsmanager:PutResourcePolicy"],

    ["ssm:SendCommand"],
    ["ssm:StartSession"],
    ["ssm:ResumeSession"],

    ["states:UpdateStateMachine"],

    ["sts:AssumeRole"],
    ["sts:AssumeRoleWithSAML"],
    ["sts:AssumeRoleWithWebIdentity"],
    ["codeartifact:GetAuthorizationToken", "sts:GetServiceBearerToken"],
    [
        "bedrock-agentcore:GetWorkloadAccessTokenForUserId",
        "bedrock-agentcore:GetResourceApiKey",
        "secretsmanager:GetSecretValue",
    ],
]

sensitive_combinations = [
    ["account:GetContactInformation"],
    ["amplify:GetApp"],
    ["amplify:GetArtifactUrl"],
    ["amplify:GetJob"],
    ["appconfig:GetHostedConfigurationVersion"],
    ["appconfig:StartConfigurationSession", "appconfig:GetLatestConfiguration"],
    ["appsync:GraphQL"],
    ["appsync:ListApiKeys"],
    ["appstream:CreateStreamingURL"],
    ["athena:GetQueryExecution"],
    ["autoscaling:DescribeLaunchConfigurations"],
    ["backup:DeleteRecoveryPoint"],
    ["backup:StartRestoreJob", "iam:PassRole"],
    [
        "backup:CreateBackupAccessPoint",
        "backup:DescribeBackupAccessPoint",
        "s3:CreateAccessPoint",
        "s3:GetAccessPoint",
        "s3:PutAccessPointPolicy",
    ],
    ["batch:DescribeJobDefinitions"],
    ["bedrock:Retrieve"],
    ["bedrock-agentcore:GetWorkloadAccessTokenForUserId"],
    ["cloudfront:GetFunction"],
    ["cloudformation:DescribeStacks"],
    ["cloudformation:DescribeChangeSet"],
    ["cloudformation:GetTemplate"],
    ["cloudformation:GetTemplateSummary"],
    ["cloudformation:ListExports"],
    ["cloudtrail:LookupEvents"],
    ["ce:GetCostAndUsage"],
    ["cloudfront:GetDistribution"],
    ["cloudfront:GetDistributionConfig"],
    ["cloudfront:ListDistributions"],
    ["codebuild:BatchGetBuilds"],
    ["codebuild:BatchGetProjects"],
    ["codeartifact:GetPackageVersionAsset"],
    ["codecommit:GetBlob"],
    ["codecommit:GetCommit"],
    ["codecommit:GetFile"],
    ["codecommit:GitPull"],
    ["codepipeline:PollForJobs"],
    ["connect:GetAttachedFile"],
    ["connect:GetFederationToken"],
    ["cognito-idp:AdminGetUser"],
    ["cognito-idp:DescribeUserPoolClient"],
    ["cognito-idp:DescribeIdentityProvider"],
    ["cognito-idp:ListUsers"],
    ["cognito-idp:ListUsersInGroup"],
    ["dynamodb:TransactGetItems"],
    ["deadline:AssumeQueueRoleForRead"],
    ["deadline:AssumeQueueRoleForUser"],
    ["ec2:DescribeLaunchTemplateVersions"],
    ["ec2:DescribeInstanceAttribute"],
    ["ebs:GetSnapshotBlock"],
    ["ecr:GetDownloadUrlForLayer"],
    ["ecs:DescribeTaskDefinition"],
    ["ecs:DescribeTasks"],
    ["emr-serverless:GetApplication"],
    ["emr-serverless:GetJobRun"],
    ["events:ListTargetsByRule"],
    ["execute-api:Invoke"],
    ["glue:GetConnection"],
    ["glue:GetJob"],
    ["glue:GetWorkflowRunProperties"],
    ["greengrass:GetComponentVersionArtifact"],
    ["imagebuilder:GetComponent"],
    ["iot:GetThingShadow"],
    ["iot:Publish"],
    ["iot:Connect", "iot:Subscribe", "iot:Receive"],
    ["iotwireless:GetWirelessDevice"],
    ["ivschat:CreateChatToken"],
    ["kinesis:GetRecords"],
    ["kinesisanalytics:DescribeApplication"],
    ["lambda:GetFunctionConfiguration"],
    ["lambda:GetLayerVersion"],
    ["lex:CreateExport", "lex:DescribeExport"],
    ["logs:FilterLogEvents"],
    ["logs:GetLogRecord"],
    ["logs:GetLogEvents"],
    ["logs:GetQueryResults"],
    ["invoicing:BatchGetInvoiceProfile"],
    ["invoicing:GetInvoicePDF"],
    ["invoicing:ListInvoiceSummaries"],
    ["lambda:GetFunction"],
    ["route53domains:GetDomainDetail"],
    ["s3:GetDataAccess"],
    ["s3vectors:GetVectors"],
    ["s3vectors:ListVectors", "s3vectors:GetVectors"],
    ["s3vectors:QueryVectors", "s3vectors:GetVectors"],
    ["s3express:CreateSession"],
    ["sagemaker:DescribeModel"],
    ["sagemaker:DescribeTrainingJob"],
    ["ses:GetSuppressedDestination"],
    ["ses:GetEmailTemplate"],
    ["ses:ListSuppressedDestinations"],
    ["sns:ListSubscriptions"],
    ["sns:ListSubscriptionsByTopic"],
    ["sqs:ReceiveMessage"],
    ["scheduler:GetSchedule"],
    ["pipes:DescribePipe"],
    ["profile:SearchProfiles"],
    ["ssm:GetDocument"],
    ["ssm:GetOpsItem"],
    ["ssm:GetParameterHistory"],
    ["states:DescribeStateMachine"],
    ["states:DescribeExecution"],
    ["states:GetActivityTask"],
    ["states:GetExecutionHistory"],
    ["sts:GetFederationToken"],
    ["tax:GetTaxRegistration"],
    ["tax:ListTaxRegistrations"],
    ["transcribe:GetTranscriptionJob"],
    ["wisdom:GetContent"],

    ["apigateway:POST"],
    ["apigateway:GET"],
    ["apigateway:PUT"],
    ["apigateway:PATCH"],
    ["apigateway:UpdateRestApiPolicy"],

    ["chime:CreateApiKey"],

    ["codebuild:CreateProject"],
    ["codebuild:UpdateProject"],

    ["s3:GetObject"],
    ["s3:PutObject"],

    ["codepipeline:CreatePipeline", "codebuild:CreateProject", "codepipeline:StartPipelineExecution"],

    ["codestar:CreateProject"],

    ["cloudformation:CreateStack"],
    ["cloudformation:UpdateStack"],
    ["cloudformation:UpdateStackSet"],
    ["cloudformation:SetStackPolicy"],
    ["cloudformation:CreateChangeSet", "cloudformation:ExecuteChangeSet"],

    ["cognito-identity:SetIdentityPoolRoles"],
    ["cognito-idp:CreateGroup", "cognito-idp:UpdateGroup"],
    ["cognito-idp:AdminEnableUser"],
    ["cognito-idp:AdminInitiateAuth"], 
    ["cognito-idp:AdminRespondToAuthChallenge"],

    ["datapipeline:CreatePipeline"],
    ["datapipeline:PutPipelineDefinition"],
    ["datapipeline:ActivatePipeline"],

    ["dynamodb:BatchGetItem"],
    ["dynamodb:GetItem"],
    ["dynamodb:Query"],
    ["dynamodb:Scan"],
    ["dynamodb:PartiQLSelect"],
    ["dynamodb:ExportTableToPointInTime"],
    ["dynamodb:RestoreTableFromBackup"],
    ["dynamodb:PutItem"],
    ["dynamodb:UpdateItem"],

    ["athena:GetQueryResults", "s3:GetObject"],

    ["ec2:CreateSnapshot"],
    ["ec2:RunInstances"],
    ["iam:AddRoleToInstanceProfile"],
    ["ec2:AssociateIamInstanceProfile", "ec2:DisassociateIamInstanceProfile"],
    ["ec2:ReplaceIamInstanceProfileAssociation"],
    ["autoscaling:CreateLaunchConfiguration", "autoscaling:CreateAutoScalingGroup"],
    ["ec2:DescribeLaunchTemplates", "ec2:DescribeLaunchTemplateVersions"],
    ["ec2:DescribeInstances", "ec2:RunInstances", "ec2:CreateSecurityGroup", "ec2:AuthorizeSecurityGroupIngress", "ec2:CreateTrafficMirrorTarget", "ec2:CreateTrafficMirrorSession", "ec2:CreateTrafficMirrorFilter", "ec2:CreateTrafficMirrorFilterRule"],

    ["ecr:GetAuthorizationToken", "ecr:BatchGetImage", "ecr:GetDownloadUrlForLayer"],

    ["ecs:RunTask"],
    ["ecs:StartTask"],
    ["ecs:UpdateService"],
    ["ecs:CreateService"],
    ["ecs:UpdateServicePrimaryTaskSet"],

    ["elasticfilesystem:ClientMount"],
    ["elasticfilesystem:ClientRootAccess"],
    ["elasticfilesystem:ClientWrite"],
    ["elasticfilesystem:CreateMountTarget"],
    ["elasticfilesystem:ModifyMountTargetSecurityGroups"],
    ["elasticfilesystem:CreateAccessPoint"],

    ["elasticbeanstalk:RebuildEnvironment"],
    ["elasticbeanstalk:CreateApplication", "elasticbeanstalk:CreateEnvironment", "elasticbeanstalk:CreateApplicationVersion", "elasticbeanstalk:UpdateEnvironment"],
    ["elasticbeanstalk:CreateApplicationVersion", "elasticbeanstalk:UpdateEnvironment", "cloudformation:GetTemplate", "cloudformation:DescribeStackResources", "cloudformation:DescribeStackResource", "autoscaling:DescribeAutoScalingGroups", "autoscaling:SuspendProcesses", "autoscaling:SuspendProcesses"],
    ["elasticbeanstalk:DescribeConfigurationSettings", "s3:CreateBucket", "s3:GetBucketLocation", "s3:GetObject", "s3:ListBucket"],

    ["elasticmapreduce:RunJobFlow"],
    
    ["scheduler:CreateSchedule", "scheduler:UpdateSchedule"],

    ["glue:CreateDevEndpoint"],
    ["glue:CreateJob"],
    ["glue:StartJobRun"],
    ["glue:CreateTrigger"],

    ["kms:CreateKey", "kms:ReplicateKey"],
    ["kms:Decrypt"],

    ["lambda:CreateFunction"],
    ["lambda:InvokeFunction"],
    ["lambda:InvokeFunctionUrl"],
    ["lambda:CreateEventSourceMapping"],

    ["rds:AddRoleToDBCluster"],
    ["rds:CreateDBInstance"],
    ["rds:AddRoleToDBInstance"],
    ["rds:RestoreDBInstanceFromDBSnapshot"],
    ["rds:DownloadDBLogFilePortion"],
    ["rds:StartExportTask"],

    ["redshift:ModifyCluster"],

    ["sns:Publish"],
    ["sns:Subscribe"],
    ["sns:Unsubscribe"],
    
    ["sqs:SendMessage"],
    ["sqs:ReceiveMessage", "sqs:DeleteMessage", "sqs:ChangeMessageVisibility"],
    ["sqs:PurgeQueue"],

    ["sso:DetachManagedPolicyFromPermissionSet"],
    ["sso:DetachCustomerManagedPolicyReferenceFromPermissionSet"],
    ["sso:DeleteInlinePolicyFromPermissionSet"],
    ["sso:DeletePermissionsBoundaryFromPermissionSet"],

    ["s3:PutBucketNotification"],
    ["s3:PutObject"],
    ["s3:GetObject"],

    ["sagemaker:CreateNotebookInstance"],
    ["sagemaker:CreateProcessingJob"],
    ["sagemaker:CreateTrainingJob"],
    ["sagemaker:CreateHyperParameterTuningJob"],

    ["ses:SendEmail"],
    ["ses:SendRawEmail"],
    ["ses:SendTemplatedEmail"],
    ["ses:SendBulkTemplatedEmail"],
    ["ses:SendBulkEmail"],
    ["ses:SendBounce"],
    ["ses:SendCustomVerificationEmail"],

    ["ssm:GetParameter"],
    ["ssm:GetParameters"],
    ["ssm:ListCommands"],
    ["ssm:GetCommandInvocation"],

    ["states:TestState"],
    ["states:CreateStateMachine"],
    ["states:RevealSecrets"],

    ["workdocs:CreateUser"],
    ["workdocs:AddResourcePermissions"],
    ["workdocs:AddUserToGroup"],

    ["dlm:CreateLifecyclePolicy"]
]


# Live-tested high-impact attack paths and their service-specific HackTricks
# evidence. Keep this deliberately narrow: documentation-only candidates do
# not belong here.
tested_risk_documentation = {
    "backup:DeleteRecoveryPoint": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "backup:PutBackupVaultAccessPolicy": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "iot:OpenTunnel": "aws-services/aws-iot-core-enum.md",
    "iot:Publish": "aws-services/aws-iot-core-enum.md",
    "lambda:GetFunction": "aws-privilege-escalation/aws-lambda-privesc/README.md",
    "route53domains:GetDomainDetail": "aws-privilege-escalation/aws-route53-domains-privesc/README.md",
    "s3:PutAccessPointPolicy": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "sts:GetFederationToken": "aws-privilege-escalation/aws-sts-privesc/README.md",
}


live_validated_disclosure_documentation = {
    "account:GetContactInformation": "aws-services/aws-account-management-enum.md",
    "amplify:GetApp": "aws-privilege-escalation/aws-amplify-privesc/README.md",
    "amplify:GetArtifactUrl": "aws-privilege-escalation/aws-amplify-privesc/README.md",
    "amplify:GetJob": "aws-privilege-escalation/aws-amplify-privesc/README.md",
    "apigateway:GET": "aws-services/aws-api-gateway-enum.md",
    "athena:GetQueryExecution": "aws-services/aws-s3-athena-and-glacier-enum.md",
    "appstream:CreateStreamingURL": "aws-services/aws-workspaces-enum.md",
    "appconfig:GetHostedConfigurationVersion": "aws-services/aws-appconfig-enum.md",
    "appconfig:StartConfigurationSession": "aws-services/aws-appconfig-enum.md",
    "appconfig:GetLatestConfiguration": "aws-services/aws-appconfig-enum.md",
    "appsync:GraphQL": "aws-services/aws-appsync-enum.md",
    "appsync:ListApiKeys": "aws-services/aws-appsync-enum.md",
    "autoscaling:DescribeLaunchConfigurations": "aws-services/aws-ec2-ebs-elb-ssm-vpc-and-vpn-enum/README.md",
    "backup:CreateBackupAccessPoint": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "backup:DescribeBackupAccessPoint": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "backup:StartRestoreJob": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "batch:DescribeJobDefinitions": "aws-services/aws-batch-enum.md",
    "bedrock:Retrieve": "aws-services/aws-bedrock-enum.md",
    "bedrock-agentcore:GetWorkloadAccessTokenForUserId": "aws-services/aws-bedrock-enum.md",
    "bedrock-agentcore:GetResourceApiKey": "aws-services/aws-bedrock-enum.md",
    "cloudformation:DescribeStacks": "aws-services/aws-cloudformation-and-codestar-enum.md",
    "cloudformation:DescribeChangeSet": "aws-services/aws-cloudformation-and-codestar-enum.md",
    "cloudformation:GetTemplate": "aws-services/aws-cloudformation-and-codestar-enum.md",
    "cloudformation:GetTemplateSummary": "aws-services/aws-cloudformation-and-codestar-enum.md",
    "cloudformation:ListExports": "aws-services/aws-cloudformation-and-codestar-enum.md",
    "cloudfront:GetDistribution": "aws-services/aws-cloudfront-enum.md",
    "cloudfront:GetDistributionConfig": "aws-services/aws-cloudfront-enum.md",
    "cloudfront:GetFunction": "aws-services/aws-cloudfront-enum.md",
    "cloudfront:ListDistributions": "aws-services/aws-cloudfront-enum.md",
    "cloudtrail:LookupEvents": "aws-services/aws-security-and-detection-services/aws-cloudtrail-enum.md",
    "ce:GetCostAndUsage": "aws-services/aws-security-and-detection-services/aws-cost-explorer-enum.md",
    "codebuild:BatchGetBuilds": "aws-privilege-escalation/aws-codebuild-privesc/README.md",
    "codebuild:BatchGetProjects": "aws-privilege-escalation/aws-codebuild-privesc/README.md",
    "codeartifact:GetPackageVersionAsset": "aws-services/aws-codeartifact-enum.md",
    "codecommit:GetBlob": "aws-services/aws-datapipeline-codepipeline-codebuild-and-codecommit.md",
    "codecommit:GetCommit": "aws-services/aws-datapipeline-codepipeline-codebuild-and-codecommit.md",
    "codecommit:GetFile": "aws-services/aws-datapipeline-codepipeline-codebuild-and-codecommit.md",
    "codecommit:GitPull": "aws-services/aws-datapipeline-codepipeline-codebuild-and-codecommit.md",
    "codepipeline:PollForJobs": "aws-services/aws-datapipeline-codepipeline-codebuild-and-codecommit.md",
    "connect:GetAttachedFile": "aws-services/aws-connect-enum.md",
    "connect:GetFederationToken": "aws-services/aws-connect-enum.md",
    "cognito-idp:AdminGetUser": "aws-services/aws-cognito-enum/cognito-user-pools.md",
    "cognito-idp:DescribeUserPoolClient": "aws-services/aws-cognito-enum/cognito-user-pools.md",
    "cognito-idp:DescribeIdentityProvider": "aws-services/aws-cognito-enum/cognito-user-pools.md",
    "cognito-idp:ListUsers": "aws-services/aws-cognito-enum/cognito-user-pools.md",
    "cognito-idp:ListUsersInGroup": "aws-services/aws-cognito-enum/cognito-user-pools.md",
    "dynamodb:BatchGetItem": "aws-post-exploitation/aws-dynamodb-post-exploitation/README.md",
    "dynamodb:GetItem": "aws-post-exploitation/aws-dynamodb-post-exploitation/README.md",
    "dynamodb:Query": "aws-post-exploitation/aws-dynamodb-post-exploitation/README.md",
    "dynamodb:Scan": "aws-post-exploitation/aws-dynamodb-post-exploitation/README.md",
    "dynamodb:TransactGetItems": "aws-post-exploitation/aws-dynamodb-post-exploitation/README.md",
    "deadline:AssumeQueueRoleForRead": "aws-services/aws-deadline-cloud-enum.md",
    "deadline:AssumeQueueRoleForUser": "aws-services/aws-deadline-cloud-enum.md",
    "ec2:DescribeLaunchTemplateVersions": "aws-privilege-escalation/aws-ec2-privesc/README.md",
    "ec2:DescribeInstanceAttribute": "aws-services/aws-ec2-ebs-elb-ssm-vpc-and-vpn-enum/README.md",
    "ebs:GetSnapshotBlock": "aws-privilege-escalation/aws-ebs-privesc/README.md",
    "ecr:GetDownloadUrlForLayer": "aws-post-exploitation/aws-ecr-post-exploitation/README.md",
    "ecs:DescribeTaskDefinition": "aws-services/aws-ecs-enum.md",
    "ecs:DescribeTasks": "aws-services/aws-ecs-enum.md",
    "emr-serverless:GetApplication": "aws-services/aws-emr-enum.md",
    "emr-serverless:GetJobRun": "aws-services/aws-emr-enum.md",
    "events:ListTargetsByRule": "aws-services/eventbridgescheduler-enum.md",
    "execute-api:Invoke": "aws-services/aws-api-gateway-enum.md",
    "glue:GetConnection": "aws-post-exploitation/aws-glue-post-exploitation/README.md",
    "glue:GetJob": "aws-post-exploitation/aws-glue-post-exploitation/README.md",
    "glue:GetWorkflowRunProperties": "aws-post-exploitation/aws-glue-post-exploitation/README.md",
    "greengrass:GetComponentVersionArtifact": "aws-services/aws-greengrass-enum.md",
    "imagebuilder:GetComponent": "aws-services/aws-ec2-image-builder-enum.md",
    "iot:Connect": "aws-services/aws-iot-core-enum.md",
    "iot:GetThingShadow": "aws-services/aws-iot-core-enum.md",
    "iot:Receive": "aws-services/aws-iot-core-enum.md",
    "iot:Subscribe": "aws-services/aws-iot-core-enum.md",
    "iotwireless:GetWirelessDevice": "aws-services/aws-iot-wireless-enum.md",
    "ivschat:CreateChatToken": "aws-services/aws-ivs-chat-enum.md",
    "kinesis:GetRecords": "aws-services/aws-kinesis-data-streams-enum.md",
    "kinesisanalytics:DescribeApplication": "aws-services/aws-managed-flink-enum.md",
    "lambda:GetFunctionConfiguration": "aws-privilege-escalation/aws-lambda-privesc/README.md",
    "lambda:GetLayerVersion": "aws-privilege-escalation/aws-lambda-privesc/README.md",
    "lex:CreateExport": "aws-services/aws-lex-v2-enum.md",
    "lex:DescribeExport": "aws-services/aws-lex-v2-enum.md",
    "logs:FilterLogEvents": "aws-services/aws-security-and-detection-services/aws-cloudwatch-enum.md",
    "logs:GetLogRecord": "aws-services/aws-security-and-detection-services/aws-cloudwatch-enum.md",
    "logs:GetLogEvents": "aws-services/aws-security-and-detection-services/aws-cloudwatch-enum.md",
    "logs:GetQueryResults": "aws-services/aws-security-and-detection-services/aws-cloudwatch-enum.md",
    "invoicing:BatchGetInvoiceProfile": "aws-services/aws-invoicing-enum.md",
    "invoicing:GetInvoicePDF": "aws-services/aws-invoicing-enum.md",
    "invoicing:ListInvoiceSummaries": "aws-services/aws-invoicing-enum.md",
    "sagemaker:DescribeModel": "aws-services/aws-sagemaker-enum/README.md",
    "sagemaker:DescribeTrainingJob": "aws-services/aws-sagemaker-enum/README.md",
    "s3:GetDataAccess": "aws-services/aws-s3-athena-and-glacier-enum.md",
    "s3:CreateAccessPoint": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "s3:GetAccessPoint": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "s3:PutAccessPointPolicy": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "s3vectors:GetVectors": "aws-services/aws-bedrock-enum.md",
    "s3vectors:ListVectors": "aws-services/aws-bedrock-enum.md",
    "s3vectors:QueryVectors": "aws-services/aws-bedrock-enum.md",
    "s3express:CreateSession": "aws-services/aws-s3-athena-and-glacier-enum.md",
    "secretsmanager:GetSecretValue": "aws-services/aws-secrets-manager-enum.md",
    "ses:GetSuppressedDestination": "aws-services/aws-ses-enum.md",
    "ses:GetEmailTemplate": "aws-services/aws-ses-enum.md",
    "ses:ListSuppressedDestinations": "aws-services/aws-ses-enum.md",
    "sns:ListSubscriptions": "aws-services/aws-sns-enum.md",
    "sns:ListSubscriptionsByTopic": "aws-services/aws-sns-enum.md",
    "sqs:ReceiveMessage": "aws-post-exploitation/aws-sqs-post-exploitation/README.md",
    "scheduler:GetSchedule": "aws-services/eventbridgescheduler-enum.md",
    "pipes:DescribePipe": "aws-services/eventbridgescheduler-enum.md",
    "profile:SearchProfiles": "aws-services/aws-connect-customer-profiles-enum.md",
    "ssm:GetDocument": "aws-services/aws-ec2-ebs-elb-ssm-vpc-and-vpn-enum/README.md",
    "ssm:GetOpsItem": "aws-services/aws-ec2-ebs-elb-ssm-vpc-and-vpn-enum/README.md",
    "ssm:GetParameterHistory": "aws-privilege-escalation/aws-ssm-privesc/README.md",
    "states:DescribeStateMachine": "aws-post-exploitation/aws-stepfunctions-post-exploitation/README.md",
    "states:DescribeExecution": "aws-post-exploitation/aws-stepfunctions-post-exploitation/README.md",
    "states:GetActivityTask": "aws-post-exploitation/aws-stepfunctions-post-exploitation/README.md",
    "states:GetExecutionHistory": "aws-post-exploitation/aws-stepfunctions-post-exploitation/README.md",
    "tax:GetTaxRegistration": "aws-services/aws-tax-settings-enum.md",
    "tax:ListTaxRegistrations": "aws-services/aws-tax-settings-enum.md",
    "transcribe:GetTranscriptionJob": "aws-services/aws-transcribe-enum.md",
    "wisdom:GetContent": "aws-services/aws-q-in-connect-enum.md",
}
