

very_sensitive_combinations = [
    # Microsoft Graph application/delegated permissions exposed in token claims.
    ["AppRoleAssignment.ReadWrite.All"],
    ["Application.ReadWrite.All"],
    ["DelegatedPermissionGrant.ReadWrite.All"],
    ["RoleManagement.ReadWrite.Directory"],
    ["Policy.Read.All", "Policy.ReadWrite.ConditionalAccess"],
    ["Application.Read.All", "Policy.ReadWrite.ConditionalAccess"],
    ["PrivilegedAccess.ReadWrite.AzureAD"],
    ["PrivilegedAccess.ReadWrite.AzureResources"],
    ["UserAuthenticationMethod.ReadWrite.All"],
    ["microsoft.directory/applications/credentials/update"],
    ["microsoft.directory/applications.myOrganization/credentials/update"],
    ["microsoft.directory/applications/owners/update"],
    ["microsoft.directory/servicePrincipals/credentials/update"],
    ["microsoft.directory/servicePrincipals/synchronizationCredentials/manage"],
    ["microsoft.directory/servicePrincipals/owners/update"],
    ["microsoft.directory/servicePrincipals/getPasswordSingleSignOnCredentials", "microsoft.directory/servicePrincipals/managePasswordSingleSignOnCredentials"],
    ["microsoft.directory/groups/owners/update"],
    ["microsoft.directory/groups/members/update"],
    ["microsoft.directory/users/password/update"],
    ["microsoft.directory/deviceLocalCredentials/password/read"],
    ["microsoft.directory/bitlockerKeys/key/read"],


    ["Microsoft.Authorization/roleAssignments/write"],
    ["Microsoft.Authorization/elevateAccess/action"],

    ["Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials/write"],
    
    
    ["Microsoft.Web/sites/publish/Action"],

    ["Microsoft.Automation/automationAccounts/runbooks/draft/write", "Microsoft.Automation/automationAccounts/runbooks/draft/content/write", "Microsoft.Automation/automationAccounts/runbooks/draft/testJob/write"],
    ["Microsoft.Automation/automationAccounts/runbooks/draft/write", "Microsoft.Automation/automationAccounts/runbooks/draft/content/write", "Microsoft.Automation/automationAccounts/runbooks/publish/action", "Microsoft.Automation/automationAccounts/jobs/write"],
    ["Microsoft.Automation/automationAccounts/sourceControls/write", "Microsoft.Automation/automationAccounts/jobs/write"],

    ["Microsoft.ContainerRegistry/registries/listCredentials/action"],
    ["Microsoft.ContainerRegistry/registries/tokens/write", "Microsoft.ContainerRegistry/registries/generateCredentials/action"],
    ["Microsoft.ContainerRegistry/registries/listBuildSourceUploadUrl/action", "Microsoft.ContainerRegistry/registries/scheduleRun/action"],

    ["Microsoft.ContainerInstance/containerGroups/containers/exec/action"],
    ["Microsoft.App/containerApps/getAuthToken/action", "Microsoft.App/containerApps/exec/action"],
    ["Microsoft.App/containerApps/getAuthToken/action", "Microsoft.App/containerApps/debug/action"],


    ["Microsoft.DocumentDB/databaseAccounts/sqlRoleDefinitions/write", "Microsoft.DocumentDB/databaseAccounts/sqlRoleAssignments/write"],
    ["Microsoft.DocumentDB/databaseAccounts/mongodbRoleDefinitions/write", "Microsoft.DocumentDB/databaseAccounts/mongodbUserDefinitions/write"],

    ["Microsoft.DocumentDB/databaseAccounts/listKeys/action"],
    ["Microsoft.DocumentDB/mongoClusters/write"],

    ["Microsoft.Web/sites/host/listkeys/action"],
    ["Microsoft.Web/sites/slots/host/listkeys/action"],
    ["Microsoft.Web/sites/functions/listkeys/action"],
    ["Microsoft.Web/sites/slots/functions/listkeys/action"],
    ["Microsoft.Web/sites/host/functionKeys/write"],
    ["Microsoft.Web/sites/config/list/action"],
    ["Microsoft.Web/sites/config/list/action", "Microsoft.Web/sites/config/write"],
    ["Microsoft.Web/sites/publishxml/action"],
    ["Microsoft.Web/sites/config/write", "Microsoft.Web/sites/config/list/action"],

    ["Microsoft.Logic/workflows/write"],
    ["Microsoft.Web/sites/basicPublishingCredentialsPolicies/read", "Microsoft.Web/sites/write", "Microsoft.Web/sites/config/list/action"],

    ["Microsoft.DBforMySQL/flexibleServers/write"],
    ["Microsoft.DBforMySQL/flexibleServers/write", "Microsoft.DBforMySQL/flexibleServers/backups/read"],
    ["Microsoft.DBforMySQL/flexibleServers/administrators/write"],

    ["Microsoft.DBforPostgreSQL/flexibleServers/write"],
    ["Microsoft.DBforPostgreSQL/flexibleServers/write", "Microsoft.DBforPostgreSQL/flexibleServers/backups/read"],
    ["Microsoft.DBforPostgreSQL/flexibleServers/administrators/write"],

    ["Microsoft.ServiceBus/namespaces/authorizationrules/listKeys/action"],
    ["Microsoft.ServiceBus/namespaces/authorizationrules/regenerateKeys/action"],
    ["Microsoft.ServiceBus/namespaces/*/authorizationRules/ListKeys/action"],
    ["Microsoft.ServiceBus/namespaces/*/authorizationRules/regenerateKeys/action"],

    ["Microsoft.Web/staticSites/listSecrets/action"],

    ["Microsoft.Storage/storageAccounts/listkeys/action"],
    ["Microsoft.Storage/storageAccounts/regenerateKey/action"],
    ["Microsoft.Storage/storageAccounts/fileServices/takeOwnership/action"],
    ["Microsoft.Storage/storageAccounts/fileServices/fileshares/files/modifypermissions/action"],
    ["Microsoft.Storage/storageAccounts/fileServices/fileshares/files/actassuperuser/action"],
    ["Microsoft.Storage/storageAccounts/localusers/write"],
    ["Microsoft.Storage/storageAccounts/localusers/regeneratePassword/action"],

    ["Microsoft.ApiManagement/service/users/token/action"],
    ["Microsoft.AppConfiguration/configurationStores/ListKeys/action"],
    ["Microsoft.AppConfiguration/configurationStores/RegenerateKey/action"],
    ["Microsoft.Automation/automationAccounts/listKeys/action"],
    ["Microsoft.Batch/batchAccounts/listkeys/action"],
    ["Microsoft.Cache/redis/listKeys/action"],
    ["Microsoft.CognitiveServices/accounts/listKeys/action"],
    ["Microsoft.DataFactory/datafactories/gateways/listauthkeys/action"],
    ["Microsoft.DataFactory/factories/integrationruntimes/listauthkeys/action"],
    ["Microsoft.EventHub/namespaces/authorizationRules/listkeys/action"],
    ["Microsoft.EventHub/namespaces/eventhubs/authorizationRules/listkeys/action"],
    ["Microsoft.Devices/IotHubs/listkeys/action"],
    ["Microsoft.Devices/IotHubs/iotHubKeys/listkeys/action"],
    ["Microsoft.KeyVault/vaults/accessPolicies/write"],
    ["Microsoft.KeyVault/vaults/deploy/action", "Microsoft.Resources/deployments/write"],
    ["Microsoft.Search/searchServices/listAdminKeys/action"],
    ["Microsoft.Storage/storageAccounts/listAccountSas/action"],
    ["Microsoft.Storage/storageAccounts/listServiceSas/action"],
    ["Microsoft.NotificationHubs/Namespaces/authorizationRules/listkeys/action"],
    ["Microsoft.NotificationHubs/Namespaces/authorizationRules/regenerateKeys/action"],
    ["Microsoft.NotificationHubs/Namespaces/NotificationHubs/authorizationRules/listkeys/action"],
    ["Microsoft.NotificationHubs/Namespaces/NotificationHubs/authorizationRules/regenerateKeys/action"],
    ["Microsoft.Web/containerApps/listsecrets/action"],
    ["Microsoft.App/containerApps/listSecrets/action"],

    ["Microsoft.ContainerService/managedClusters/listClusterAdminCredential/action"],
    ["Microsoft.HybridContainerService/provisionedClusters/listClusterAdminCredential/action"],

    ["Microsoft.Compute/virtualMachines/runCommands/write"],
    ["Microsoft.Compute/virtualMachineScaleSets/virtualMachines/runCommands/write"],
    ["Microsoft.HybridCompute/machines/runcommands/write"],

    ["Microsoft.Sql/servers/write"],
    ["Microsoft.Sql/servers/administrators/write"],
    ["Microsoft.Sql/servers/azureADOnlyAuthentications/write"],
    ["Microsoft.Sql/servers/databases/dataMaskingPolicies/write"],
    
    ["Microsoft.DesktopVirtualization/hostPools/retrieveRegistrationToken/action"],

    ["Microsoft.Compute/virtualMachines/extensions/write"],
    ["Microsoft.Compute/virtualMachines/runCommand/action"],
    ["Microsoft.Compute/virtualMachines/loginAsAdmin/action"],

    ["Microsoft.KeyVault/vaults/secrets/getSecret/action"],

]

sensitive_combinations = [
    ["AuditLog.Read.All"],
    ["Directory.Read.All"],
    ["Directory.ReadWrite.All"],
    ["Group.ReadWrite.All"],
    ["Mail.Read"],
    ["Mail.ReadWrite"],
    ["RoleManagement.Read.Directory"],
    ["User.Read.All"],
    ["User.ReadWrite.All"],
    ["microsoft.directory/applications/allProperties/update"],
    ["microsoft.directory/groups/dynamicMembershipRule/update"],
    ["microsoft.directory/devices/registeredOwners/update"],
    ["microsoft.directory/devices/registeredUsers/update"],
    ["Microsoft.Authorization/roleDefinitions/Write"],
    ["Microsoft.ManagedIdentity/userAssignedIdentities/assign/action"],
    ["Microsoft.Automation/automationAccounts/schedules/write", "Microsoft.Automation/automationAccounts/jobSchedules/write"],
    ["Microsoft.Automation/automationAccounts/sourceControls/write"],
    ["Microsoft.ContainerRegistry/registries/tasks/write"],
    ["Microsoft.ContainerRegistry/registries/importImage/action"],
    ["Microsoft.App/containerApps/getAuthToken/action"],
    ["Microsoft.App/jobs/write"],
    ["Microsoft.Web/staticSites/createInvitation/action"],
    ["Microsoft.ContainerService/managedClusters/listClusterUserCredential/action"],
    ["Microsoft.Kubernetes/connectedClusters/listClusterUserCredential/action"],
    ["Microsoft.Kubernetes/connectedClusters/listClusterUserCredentials/action"],
    ["Microsoft.HybridContainerService/provisionedClusters/listClusterUserCredential/action"],
    ["Microsoft.Compute/virtualMachines/login/action"],
    ["Microsoft.Compute/galleries/applications/versions/write"],
    ["Microsoft.Resources/deploymentScripts/write"],
    ["Microsoft.EventGrid/topics/listKeys/action"],
    ["Microsoft.EventGrid/topics/regenerateKey/action"],
    ["Microsoft.EventGrid/domains/listKeys/action"],
    ["Microsoft.EventGrid/domains/regenerateKey/action"],
    ["Microsoft.EventGrid/namespaces/listKeys/action"],
    ["Microsoft.EventGrid/namespaces/regenerateKey/action"],
    ["Microsoft.EventGrid/namespaces/topics/listKeys/action"],
    ["Microsoft.EventGrid/namespaces/topics/regenerateKey/action"],
    ["Microsoft.EventGrid/partnerNamespaces/listKeys/action"],
    ["Microsoft.EventGrid/partnerNamespaces/regenerateKey/action"],
    ["Microsoft.OperationalInsights/workspaces/listKeys/action"],
    ["Microsoft.OperationalInsights/workspaces/regenerateSharedKey/action"],
    ["Microsoft.OperationalInsights/workspaces/sharedKeys/action"],
    ["Microsoft.OperationalInsights/workspaces/sharedKeys/read"],
    ["Microsoft.Communication/CommunicationServices/ListKeys/action"],
    ["Microsoft.Communication/CommunicationServices/RegenerateKey/action"],
    ["Microsoft.Relay/namespaces/authorizationRules/listkeys/action"],
    ["Microsoft.Relay/namespaces/authorizationRules/regenerateKeys/action"],
    ["Microsoft.Relay/namespaces/HybridConnections/authorizationRules/listkeys/action"],
    ["Microsoft.Relay/namespaces/HybridConnections/authorizationRules/regeneratekeys/action"],
    ["Microsoft.Relay/namespaces/WcfRelays/authorizationRules/listkeys/action"],
    ["Microsoft.Relay/namespaces/WcfRelays/authorizationRules/regeneratekeys/action"],
    ["Microsoft.SignalRService/SignalR/listkeys/action"],
    ["Microsoft.SignalRService/SignalR/regeneratekey/action"],
    ["Microsoft.SignalRService/WebPubSub/listkeys/action"],
    ["Microsoft.SignalRService/WebPubSub/regeneratekey/action"],
    ["Microsoft.Web/sites/hostruntime/vfs/read"],
    ["Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read"],
    ["Microsoft.Storage/storageAccounts/fileServices/fileshares/files/read"],
    ["Microsoft.Storage/storageAccounts/queueServices/queues/messages/read"],
    ["Microsoft.Storage/storageAccounts/tableServices/tables/entities/read"]
]
